[project]
name = "spanglishtemp"
version = "1.4.1"
description = "A CLI tool to help you learn Spanish vocabulary effectively."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bump2version>=1.0.1",
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "pydantic>=2.12.0",
    "prompt-toolkit>=3.0.52",
    "pytest>=9.0.1",
    "questionary>=2.1.1",
    "rich>=14.2.0",
    "ruff>=0.14.7",
    "typer>=0.20.0",
    "r2d2-sdk-auth",
]

# configure Ruff linter
[tool.ruff]
line-length = 88
exclude = ["__init__.py"]

[tool.ruff.lint]
select = ["E", "F", "W", "C90", "B", "I", "Q000"]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[tool.uv.sources]
r2d2-sdk-auth = { git = "https://github.com/fedal-nl/r2d2-sdk-auth.git" }
