"""adjusted the quiz_attempt to have a content_type and id

Revision ID: 172f90b2a656
Revises: d6807138982b
Create Date: 2025-12-04 21:22:04.184292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172f90b2a656'
down_revision: Union[str, Sequence[str], None] = 'd6807138982b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    quiz_content_type = sa.Enum(
        "WORD",
        "SENTENCE",
        name="quizcontenttypeenum"
    )
    quiz_content_type.create(op.get_bind())
    
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.Enum('WORD', 'SENTENCE', name='quizcontenttypeenum'), nullable=False))
        batch_op.add_column(sa.Column('content_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_quiz_attempts_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_content_type'), ['content_type'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_quizattempt_word_id_words'), type_='foreignkey')
        batch_op.drop_column('word_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_quizattempt_word_id_words'), 'words', ['word_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_content_type'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_content_id'))
        batch_op.drop_column('content_id')
        batch_op.drop_column('content_type')

    # ### end Alembic commands ###
