"""remove words, sentence and adjusting relations

Revision ID: 1b8e0a9e71a4
Revises: e2bedf1a48ac
Create Date: 2025-12-08 19:33:48.593838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b8e0a9e71a4'
down_revision: Union[str, Sequence[str], None] = 'e2bedf1a48ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE contenttypeenum AS ENUM ('WORD', 'SENTENCE')")

    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentences_created_at'))
        batch_op.drop_index(batch_op.f('ix_sentences_topic'))


    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_words_category'))
        batch_op.drop_index(batch_op.f('ix_words_created_at'))
        batch_op.drop_index(batch_op.f('ix_words_id'))
        batch_op.drop_index(batch_op.f('ix_words_word'))

    
    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.Enum('WORD', 'SENTENCE', name='contenttypeenum'), nullable=False))
        batch_op.create_index(batch_op.f('ix_dictionary_content_type'), ['content_type'], unique=False)

    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dictionary_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_content_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_content_type'))
        batch_op.create_foreign_key('fk_quizattempt_dictionary_id_dictionary', 'dictionary', ['dictionary_id'], ['id'])
        batch_op.drop_column('content_id')
        batch_op.drop_column('content_type')

    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_translation_word_id_words'), type_='foreignkey')
        batch_op.drop_column('word_id')

    with op.batch_alter_table('verbs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dictionary_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['dictionary_id'])
        batch_op.drop_constraint(batch_op.f('fk_verb_word_id_words'), type_='foreignkey')
        batch_op.create_foreign_key('fk_verb_dictionary_id_dictionary', 'dictionary', ['dictionary_id'], ['id'])
        batch_op.drop_column('word_id')

    op.drop_table('sentences')
    op.drop_table('words')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verbs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_verb_dictionary_id_dictionary', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_verb_word_id_words'), 'words', ['word_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('dictionary_id')

    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_translation_word_id_words'), 'words', ['word_id'], ['id'])

    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.VARCHAR(length=8), nullable=False))
        batch_op.add_column(sa.Column('content_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_quizattempt_dictionary_id_dictionary', type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_quiz_attempts_content_type'), ['content_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_content_id'), ['content_id'], unique=False)
        batch_op.drop_column('dictionary_id')

    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dictionary_content_type'))
        batch_op.drop_column('content_type')

    op.create_table('words',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('word', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=10), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word', 'category')
    )
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_words_word'), ['word'], unique=False)
        batch_op.create_index(batch_op.f('ix_words_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_words_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_words_category'), ['category'], unique=False)

    op.create_table('sentences',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('spanish', sa.VARCHAR(), nullable=False),
    sa.Column('english', sa.VARCHAR(), nullable=False),
    sa.Column('topic', sa.VARCHAR(length=10), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spanish', 'english')
    )
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentences_topic'), ['topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentences_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###
