"""set the name to the enum column

Revision ID: 248791f4ed44
Revises: d1bcc5bcd523
Create Date: 2026-01-06 19:28:21.566906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '248791f4ed44'
down_revision: Union[str, Sequence[str], None] = 'd1bcc5bcd523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### This migration is only to fix the enum column name and values of the mergedcategory enum on postgresql ###
    conn = op.get_context().dialect.name
    if conn == 'postgresql':
        op.drop_table('words')
        with op.batch_alter_table('dictionary', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_dictionary_content_type'))
            batch_op.drop_column('content_type')

            values = (
                'NOUN', 'VERB', 'ADJECTIVE', 'DAY', 'MONTH', 'COLOR',
                'BODY_PART', 'ANIMAL', 'FAMILY', 'NUMBERS', 'TIME',
                'DIRECTIONS', 'GREETINGS', 'WEATHER', 'SONGS', 'FOOD'
            )

            op.execute("COMMIT")  # required on PG < 12

            for v in values:
                op.execute(
                    f"ALTER TYPE mergedcategory ADD VALUE IF NOT EXISTS '{v}'"
                )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', postgresql.ENUM('WORD', 'SENTENCE', name='contenttypeenum'), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('ix_dictionary_content_type'), ['content_type'], unique=False)

    op.create_table('words',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('word', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('NOUN', 'VERB', 'ADJECTIVE', 'DAY', 'MONTH', 'FOOD', 'COLOR', 'BODY_PART', 'ANIMAL', 'FAMILY', 'NUMBERS', 'TIME', 'DIRECTIONS', 'GREETINGS', 'WEATHER', 'SONGS', name='categoryenum'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('words_pkey')),
    sa.UniqueConstraint('word', 'category', name=op.f('words_word_category_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
