"""<migration_message>

Revision ID: 3963f5b7f37f
Revises: 248791f4ed44
Create Date: 2026-01-07 19:56:28.087906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3963f5b7f37f'
down_revision: Union[str, Sequence[str], None] = '248791f4ed44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_context().dialect.name
    if conn == 'postgresql':
        # PostgreSQL enums must be altered explicitly
        op.execute("COMMIT")
        op.execute("ALTER TYPE mergedcategory ADD VALUE IF NOT EXISTS 'PROFESSIONS'")
    else:
        with op.batch_alter_table('dictionary', schema=None) as batch_op:
            batch_op.alter_column('category',
                existing_type=sa.VARCHAR(length=10),
                type_=sa.Enum('NOUN', 'VERB', 'ADJECTIVE', 'DAY', 'MONTH', 'COLOR', 'BODY_PART', 'ANIMAL', 'FAMILY', 'NUMBERS', 'TIME', 'DIRECTIONS', 'GREETINGS', 'WEATHER', 'SONGS', 'FOOD', 'PROFESSIONS', name='mergedcategory'),
                existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.Enum('NOUN', 'VERB', 'ADJECTIVE', 'DAY', 'MONTH', 'COLOR', 'BODY_PART', 'ANIMAL', 'FAMILY', 'NUMBERS', 'TIME', 'DIRECTIONS', 'GREETINGS', 'WEATHER', 'SONGS', 'FOOD', 'PROFESSIONS', name='mergedcategory'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
