"""added answer column to quiz_attempt

Revision ID: 4cef1c079163
Revises: 1b8e0a9e71a4
Create Date: 2025-12-08 21:36:31.675089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cef1c079163'
down_revision: Union[str, Sequence[str], None] = '1b8e0a9e71a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        # drop the existing indexes before adding the new column
        op.execute('DROP INDEX IF EXISTS ix_quiz_attempts_answered_at')
        op.execute('DROP INDEX IF EXISTS ix_quiz_attempts_answered_correctly')
        
        batch_op.add_column(sa.Column('answer', sa.String(), nullable=False))
        batch_op.create_index(batch_op.f('ix_quiz_attempts_answered_at'), ['answered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_answered_correctly'), ['answered_correctly'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_answered_correctly'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_answered_at'))
        batch_op.drop_column('answer')

    # ### end Alembic commands ###
