"""create initial tables

Revision ID: 79ec8862fe18
Revises: 
Create Date: 2025-12-02 21:48:10.662024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ec8862fe18'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_sessions_created_at'), ['created_at'], unique=False)

    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('NOUN', 'VERB', 'ADJECTIVE', 'DAY', 'MONTH', 'FOOD', 'COLOR', 'BODY_PART', 'ANIMAL', 'FAMILY', name='categoryenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word', 'category')
    )
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_words_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_words_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_words_word'), ['word'], unique=False)

    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('answered_correctly', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], name='fk_quizattempt_session_id_quizsessions'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], name='fk_quizattempt_word_id_words'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_attempts_answered_at'), ['answered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_answered_correctly'), ['answered_correctly'], unique=False)

    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('translation', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], name='fk_translation_word_id_words'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_id', 'translation')
    )
    op.create_table('verbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('yo', sa.String(), nullable=True),
    sa.Column('tu', sa.String(), nullable=True),
    sa.Column('ella_el', sa.String(), nullable=True),
    sa.Column('nosotros', sa.String(), nullable=True),
    sa.Column('vosotros', sa.String(), nullable=True),
    sa.Column('ellos_ellas', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], name='fk_verb_word_id_words'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verbs')
    op.drop_table('translations')
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_answered_correctly'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_answered_at'))

    op.drop_table('quiz_attempts')
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_words_word'))
        batch_op.drop_index(batch_op.f('ix_words_id'))
        batch_op.drop_index(batch_op.f('ix_words_category'))

    op.drop_table('words')
    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_sessions_created_at'))

    op.drop_table('quiz_sessions')
    # ### end Alembic commands ###
