"""removed translation from Words

Revision ID: 8916430b80e3
Revises: 9faf9aa139dd
Create Date: 2025-11-27 20:47:40.186688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8916430b80e3'
down_revision: Union[str, Sequence[str], None] = '9faf9aa139dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'translation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('translation', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
