"""create quizsession and quizattempts table

Revision ID: 990dfd268d4f
Revises: d73b088a93c3
Create Date: 2025-11-29 18:45:32.298468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990dfd268d4f'
down_revision: Union[str, Sequence[str], None] = 'd73b088a93c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verbs', schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_verbs_word_id", ['word_id'])

    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_words_word", ['word'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_constraint("uq_words_word", type_='unique')

    with op.batch_alter_table('verbs', schema=None) as batch_op:
        batch_op.drop_constraint("uq_verbs_word_id", type_='unique')

    # ### end Alembic commands ###
