"""create translation table

Revision ID: 9faf9aa139dd
Revises: c6e86b6a5631
Create Date: 2025-11-26 22:02:08.363047

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9faf9aa139dd"
down_revision: Union[str, Sequence[str], None] = "c6e86b6a5631"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("translations",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("word_id", sa.Integer(), nullable=False),
    sa.Column("translation", sa.String(), nullable=False),
    sa.ForeignKeyConstraint(["word_id"], ["words.id"], ),
    sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("translations")
    # ### end Alembic commands ###
