"""create words and verbs tables

Revision ID: c6e86b6a5631
Revises: 
Create Date: 2025-11-25 22:50:02.672106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e86b6a5631'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('NOUN', 'VERB', 'ADJECTIVE', 'DAY', 'MONTH', 'FOOD', name='categoryenum'), nullable=False),
    sa.Column('translation', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_id'), 'words', ['id'], unique=False)
    op.create_table('verbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('yo', sa.String(), nullable=True),
    sa.Column('tu', sa.String(), nullable=True),
    sa.Column('ella_el', sa.String(), nullable=True),
    sa.Column('nosotros', sa.String(), nullable=True),
    sa.Column('vosotros', sa.String(), nullable=True),
    sa.Column('ellos_ellas', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verbs')
    op.drop_index(op.f('ix_words_id'), table_name='words')
    op.drop_table('words')
    # ### end Alembic commands ###
