"""removed content type and unified categories

Revision ID: d1bcc5bcd523
Revises: 4cef1c079163
Create Date: 2025-12-09 20:12:46.625957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1bcc5bcd523'
down_revision: Union[str, Sequence[str], None] = '4cef1c079163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the ENUM type explicitly
    # category_enum = sa.Enum(
    #     'NOUN', 'VERB', 'ADJECTIVE', 'DAY', 'MONTH', 'COLOR',
    #     'BODY_PART', 'ANIMAL', 'FAMILY', 'NUMBERS', 'TIME',
    #     'DIRECTIONS', 'GREETINGS', 'WEATHER', 'SONGS', 'FOOD',
    #     name='categoryenum'
    # )
    # category_enum.create(op.get_bind(), checkfirst=True)

    # # Now convert the column using explicit cast
    # op.execute("""
    #     ALTER TABLE dictionary
    #     ALTER COLUMN category
    #     TYPE categoryenum
    #     USING category::categoryenum
    # """)

    # Drop index and remove content_type column (your existing logic)
    # with op.batch_alter_table('dictionary') as batch_op:
    #     batch_op.drop_index(batch_op.f('ix_dictionary_content_type'))
    #     batch_op.drop_column('content_type')
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_context().dialect.name
    if conn == 'postgresql':
        new_category_enum = (
            'NOUN', 'VERB', 'ADJECTIVE', 'DAY', 'MONTH', 'COLOR',
            'BODY_PART', 'ANIMAL', 'FAMILY', 'NUMBERS', 'TIME',
            'DIRECTIONS', 'GREETINGS', 'WEATHER', 'SONGS', 'FOOD'
        )
        for val in new_category_enum:
            op.execute("""ALTER TYPE categoryenum ADD VALUE IF NOT EXISTS %s""" % ("'" + val + "'"))
    else:
        with op.batch_alter_table('dictionary', schema=None) as batch_op:
            batch_op.alter_column('category',
                existing_type=sa.VARCHAR(length=4),
                type_=sa.Enum('NOUN', 'VERB', 'ADJECTIVE', 'DAY', 'MONTH', 'COLOR', 'BODY_PART', 'ANIMAL', 'FAMILY', 'NUMBERS', 'TIME', 'DIRECTIONS', 'GREETINGS', 'WEATHER', 'SONGS', 'FOOD', name='categoryenum'),
                existing_nullable=False)
            batch_op.drop_index(batch_op.f('ix_dictionary_content_type'))
            batch_op.drop_column('content_type')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.VARCHAR(length=8), nullable=False))
        batch_op.create_index(batch_op.f('ix_dictionary_content_type'), ['content_type'], unique=False)
        batch_op.alter_column('category',
               existing_type=sa.Enum('NOUN', 'VERB', 'ADJECTIVE', 'DAY', 'MONTH', 'COLOR', 'BODY_PART', 'ANIMAL', 'FAMILY', 'NUMBERS', 'TIME', 'DIRECTIONS', 'GREETINGS', 'WEATHER', 'SONGS', 'FOOD', name='categoryenum'),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)

    # ### end Alembic commands ###
