"""create sentence table

Revision ID: d6807138982b
Revises: 79ec8862fe18
Create Date: 2025-12-03 21:29:21.453177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6807138982b'
down_revision: Union[str, Sequence[str], None] = '79ec8862fe18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spanish', sa.String(), nullable=False),
    sa.Column('english', sa.String(), nullable=False),
    sa.Column('topic', sa.Enum('GREETINGS', 'WEATHER', 'DIRECTIONS', 'SONGS', 'TIME', 'FOOD', name='topicenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spanish', 'english')
    )
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentences_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentences_topic'), ['topic'], unique=False)

    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('NOUN', 'VERB', 'ADJECTIVE', 'DAY', 'MONTH', 'FOOD', 'COLOR', 'BODY_PART', 'ANIMAL', 'FAMILY', 'NUMBERS', 'TIME', 'DIRECTIONS', name='categoryenum'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_words_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_words_created_at'))
        batch_op.alter_column('category',
               existing_type=sa.Enum('NOUN', 'VERB', 'ADJECTIVE', 'DAY', 'MONTH', 'FOOD', 'COLOR', 'BODY_PART', 'ANIMAL', 'FAMILY', 'NUMBERS', 'TIME', 'DIRECTIONS', name='categoryenum'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentences_topic'))
        batch_op.drop_index(batch_op.f('ix_sentences_created_at'))

    op.drop_table('sentences')
    # ### end Alembic commands ###
