"""Added contstaint

Revision ID: d73b088a93c3
Revises: 8916430b80e3
Create Date: 2025-11-27 21:10:25.764941

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d73b088a93c3"
down_revision: Union[str, Sequence[str], None] = "8916430b80e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

bind = op.get_bind()
db_type_name = bind.dialect.name


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if db_type_name != "sqlite":
        op.create_unique_constraint(None, "translations", ["word_id", "translation"])
        op.create_unique_constraint(None, "verbs", ["word_id"])
        op.create_unique_constraint(None, "words", ["word"])
    else:
        with op.batch_alter_table("translations") as batch_op:
            batch_op.create_unique_constraint(
                "uix_word_translation",
                ["word_id", "translation"]
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if db_type_name != "sqlite":
        op.drop_constraint(None, "words", type_="unique")
        op.drop_constraint(None, "verbs", type_="unique")
        op.drop_constraint(None, "translations", type_="unique")
    else:
        with op.batch_alter_table("translations") as batch_op:
            batch_op.drop_constraint(
            "uix_word_translation",
            type_="unique"
        )
    # ### end Alembic commands ###
