"""creating dictionary and mergedcategory

Revision ID: e2bedf1a48ac
Revises: 172f90b2a656
Create Date: 2025-12-08 18:34:50.161971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2bedf1a48ac'
down_revision: Union[str, Sequence[str], None] = '172f90b2a656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('VERB', name='mergedcategory'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text', 'category')
    )
    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dictionary_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_dictionary_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dictionary_text'), ['text'], unique=False)

    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dictionary_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_translations_dictionary_id_translation', ['dictionary_id', 'translation'])
        batch_op.create_foreign_key('fk_translation_dictionary_id_dictionary', 'dictionary', ['dictionary_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_translation_dictionary_id_dictionary', type_='foreignkey')
        batch_op.drop_constraint('uq_translations_dictionary_id_translation', type_='unique')
        batch_op.drop_column('dictionary_id')

    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dictionary_text'))
        batch_op.drop_index(batch_op.f('ix_dictionary_created_at'))
        batch_op.drop_index(batch_op.f('ix_dictionary_category'))

    op.drop_table('dictionary')
    # ### end Alembic commands ###
